[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "127.0.0.1"
Port = "5432"
EnableLog = true
MaxConns = 200

[Etherman]
URL = "http://localhost:8545"
PrivateKeyPath = "/pk/keystore"
PrivateKeyPassword = "testonly"

[RPC]
Host = "0.0.0.0"
Port = 8123
MaxRequestsPerIPAndSecond = 50
ChainID = 1001
SequencerAddress = "0x617b3a3528F9cDd6630fd3301B9c8911F7Bf063D"

[RPCV2]
Host = "0.0.0.0"
Port = 8123
MaxRequestsPerIPAndSecond = 50
ChainID = 1001

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[Sequencer]
AllowNonRegistered = "true"
IntervalToProposeBatch = "5s"
SyncedBlockDif = 1
InitBatchProcessorIfDiffType = "synced"
MaxSendBatchTxRetries = 5
FrequencyForResendingFailedSendBatchesInMilliseconds = 1000
    [Sequencer.Strategy]
        [Sequencer.Strategy.TxSelector]
            Type = "acceptall"
            TxSorterType = "bycostandnonce"
        [Sequencer.Strategy.TxProfitabilityChecker]
            Type = "acceptall"
            MinReward = "1.1"
    [Sequencer.PriceGetter]
        Type = "default"
        DefaultPrice = "2000"
    [Sequencer.PendingTxsQueue]
        TxPendingInQueueCheckingFrequency = "3s"
        GetPendingTxsFrequency = "5s"

[GasPriceEstimator]
Type = "default"
DefaultGasPriceWei = 1000000000

[Aggregator]
IntervalFrequencyToGetProofGenerationStateInSeconds = "5s"
IntervalToConsolidateState = "10s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"

[Prover]
ProverURI = "zkevm-prover:50051"

[MTServer]
Host = "zkevm-prover"
Port = 50061
StoreBackend = "PostgreSQL"

[MTClient]
URI  = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[BroadcastServer]
Host = "127.0.0.1"
Port = 61090

[BroadcastClient]
URI = "127.0.0.1:61090"
